

    try {
        throw new Error("Ocurri√≥ un error");
    } catch (error) {
        console.log(error.message);
        console.log(error.stack);
    }
    






